seed: &seed 0
#log_level: 40 # ERROR
log_level: 20

dataset:
  name: OnlyDiTauDataset_wo_mass
  params:
    # max_events is 50000 + 50000 events
    max_events: 50000
    data_path: '/data/saito/dataset/onlyDiTau/'

n_jets: &n_jets 2
n_intermediate_vars: &n_intermediate_vars 6

sub_task_params:
  tau4vec:
    tasks:
      Tau4vec_MLPTask:
        params:
          layers_images: [768, 16, 16, 16, 4]
          layers_calib: [8, 32, 32, 3]
          activation: 'ReLU'
          batch_norm: False
      Tau4vec_Conv2DTask:
        params:
          layers_conv2d:
            -
              - 'conv2d'
              - {'in_channels': 3, 'out_channels': 32, 'kernel_size': 3}
            -
              - 'conv2d'
              - {'in_channels': 32, 'out_channels': 16, 'kernel_size': 3}
            -
              - 'maxpooling2d'
              - {}
            -
              - 'conv2d'
              - {'in_channels': 16, 'out_channels': 16, 'kernel_size': 2}
            -
              - 'conv2d'
              - {'in_channels': 16, 'out_channels': 8, 'kernel_size': 2}
          layers_images: [128, 16, 16, 16, 4]
          layers_calib: [8, 64, 64, 64, 3]
          activation: 'ReLU'
          batch_norm: False
      Tau4vec_SFTask:
        params:
          n_input_vars: 8
          n_output_vars: *n_intermediate_vars
          n_jets: *n_jets
    pretrain:
      epochs: 100
      patience: 10
      batch_size: 128
      optimizer:
        name: Adam
        params:
          lr: 1.0e-3
      loss_func:
        name: Tau4vecCalibLoss_torch
      metrics:
        name: Calc_R2
        params:
          multioutput: variance_weighted
      activation:
        name: False
      data:
        input_key: inputs
        target_key: internal_vec
      verbose: 1
  higgsId:
    tasks:
      HiggsID_MLPTask:
        params:
          layers: [6, 32, 32, 32, 1]
          activation: 'ReLU'
          activation_last: 'Identity'
          batch_norm: False
      HiggsID_LSTMTask:
        params:
          layers_lstm: [3, 32, 32, 32, 1]
          layers_mlp: [1, 1]
          activation_last: 'Identity'
          batch_norm: False
          n_jets: *n_jets
      HiggsID_MassTask:
        params:
          layers: [1, 64, 64, 1]
          activation: 'ReLU'
          activation_last: 'Identity'
          batch_norm: False
          scale_mass: 0.008     # 1./125.
          n_jets: *n_jets
          n_input_vars: *n_intermediate_vars
    pretrain:
      epochs: 100
      patience: 10
      batch_size: 128
      optimizer:
        name: Adam
        params:
          lr: 1.0e-3
      loss_func:
        name: BCEWithLogitsLoss
      metrics:
        name: Calc_Auc
      activation:
        name: False
      data:
        input_key: internal_vec
        target_key: internal_label
      verbose: 1
ASNG:
  epochs: 100
  batch_size: {'type':'equal_length', 'length':500, 'test' : 250}
  patience: 10
  loss_first:
    name: Tau4vecCalibLoss_torch
  loss_second:
    name: BCEWithLogitsLoss
  optimizer:
    name: Adam
    params:
      lr: 1.0e-3
  scheduler:
    name: MultiStepLR
    params:
      milestones: [50, 100]
      gamma: 1.0                # 1倍のことなので変化されない
  data:
    input_key: inputs
    target_key: targets
  asng_args : 
    alpha: 4.0
    lam: 2
    delta: 0.0
    clip: 10
    range_restriction: True 
    clipping_value: 10.0
  connectiontask_args:
    num_epochs: 1
    max_patience: 10
    batch_size: 100
    load_weights: False
    optimizer: 'Adam'
    optimizer_args: 
      lr: 1.0e-3
    verbose: 1
    metrics: ['subloss', 'auc', 'loss']
    phases: ['train', 'valid', 'test']
    variable_mapping: None
    device: None

re_train:
  epochs: 1
  optimizer:
    name: Adam
    params:
      lr: 1.0e-2
  scheduler:
    name: MultiStepLR
    params:
      milestones: [5000, 10000]
      gamma: 1.0                # 1倍のことなので変化されない
  data:
    input_key: inputs
    target_key: targets
  patience: 10
